### ISSUE TITLE
[bug] mobs spawn on top of the dungeon

### ISSUE THREAD

**Issue by Biviho** [Artur114Projects/Thaumcraft_Return_of_the_ancients#1]
hi! 
i've noticed that mobs tend to spawn a lot on top of the dungeon (all of them except for bosses in boss rooms)
do mobs have have the condition to not see sky to spawn?

**Comment by Artur114Projects** [comment]
"condition to not see sky to spawn?"
I think this is a good idea

**Comment by Biviho** [comment]
if the only condition for them to spawn was to use the slabs on the roof, is not a robust solution: there are mods that remove the not spawn on slabs condition for all mobs, a check if see sky is more robust for mobs that have to spawn in a dungeon

**Comment by Artur114Projects** [comment]
fixed, i should have done that earlier
